#pragma once

#define APP_VERSION_PART_UNDEFINED "undefined"

#ifndef APP_VERSION_MAJOR
#define APP_VERSION_MAJOR APP_VERSION_PART_UNDEFINED
#endif

#ifndef APP_VERSION_MINOR
#define APP_VERSION_MINOR APP_VERSION_PART_UNDEFINED
#endif

#ifndef APP_VERSION_PATCH
#define APP_VERSION_PATCH APP_VERSION_PART_UNDEFINED
#endif

#ifndef APP_VERSION_TWEAK
#define APP_VERSION_TWEAK APP_VERSION_PART_UNDEFINED
#endif
